language: go

go:
    - 1.11

install: skip
script: skip

jobs:
    include:
    - stage: deploy
      if: tag IS present
      script:
      - export GO111MODULE=on
      - curl -fL https://getcli.jfrog.io | sh
      - export PATH=${TRAVIS_BUILD_DIR}:$PATH
      - export GOOS=linux
      - export GOARCH=amd64
      - make dependencies
      - make deploy
